import Link from "next/link";
import { Quicksand, Inter } from "next/font/google";
import styles from "./page.module.css";

const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["600", "700"],
    variable: "--font-heading",
});

const inter = Inter({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
    variable: "--font-body",
});

export const metadata = {
    title: "Privacy Policy | DamChat",
    description:
        "How DamChat collects, uses, and protects information across the web platform and WhatsApp.",
};

const LAST_UPDATED = "September 13, 2026";

const sections = [
    {
        id: "introduction",
        title: "Introduction",
        body: (
            <>
                <p>
                    DamChat is an AI-powered document intelligence platform. Organizations
                    (&ldquo;Admins&rdquo;) upload reference documents into DamChat, and
                    authorized users (&ldquo;Users&rdquo;) ask questions about that
                    content and receive answers generated by an AI model trained on the
                    uploaded material. DamChat can be accessed through our web
                    application and, where enabled by an organization, through a chat
                    agent on WhatsApp.
                </p>
                <p>
                    This Privacy Policy explains what information we collect, how we
                    use and share it, and the choices available to you. It applies to
                    everyone who uses DamChat, whether through the web app or through
                    WhatsApp
                </p>
            </>
        ),
    },
    {
        id: "information-we-collect",
        title: "Information We Collect",
        body: (
            <>
                <p>We collect the following categories of information:</p>
                <ul>
                    <li>
                        <strong>Account information.</strong> Name, email address, role
                        (Admin or User), and organization, collected when an account is
                        created or provisioned.
                    </li>
                    <li>
                        <strong>Uploaded documents.</strong> Files that Admins upload to
                        DamChat, along with any metadata attached to them (file name,
                        upload date, uploading Admin).
                    </li>
                    <li>
                        <strong>Queries and conversation content.</strong> The questions
                        Users ask, the AI-generated answers, and related conversation
                        history, whether submitted through the web app or through
                        WhatsApp.
                    </li>
                    <li>
                        <strong>WhatsApp contact information.</strong> If you message our
                        WhatsApp agent, we receive your phone number and profile name as
                        provided by WhatsApp, along with the content and timestamps of
                        your messages.
                    </li>
                    <li>
                        <strong>Usage and device information.</strong> Log data such as
                        IP address, browser or device type, timestamps, and pages or
                        features accessed, used to keep the service secure and reliable.
                    </li>
                </ul>
            </>
        ),
    },
    {
        id: "how-we-use-information",
        title: "How We Use Your Information",
        body: (
            <>
                <p>We use the information described above to:</p>
                <ul>
                    <li>
                        Generate answers to your questions by retrieving relevant
                        passages from an organization&rsquo;s uploaded documents and
                        passing them, together with your query, to an AI model.
                    </li>
                    <li>
                        Operate, maintain, and secure DamChat, including authenticating
                        Admins and Users and enforcing access controls between
                        organizations.
                    </li>
                    <li>
                        Respond to messages sent through our WhatsApp agent and maintain
                        continuity of a conversation across sessions.
                    </li>
                    <li>
                        Monitor performance, diagnose issues, and improve the accuracy
                        and reliability of the AI system.
                    </li>
                    <li>
                        Comply with legal obligations and enforce our terms of use.
                    </li>
                </ul>
                <p>
                    We do not use uploaded documents or conversation content to train
                    general-purpose AI models outside the scope of the organization
                    that submitted them.
                </p>
            </>
        ),
    },
    {
        id: "whatsapp-integration",
        title: "WhatsApp Business Platform & Meta",
        body: (
            <>
                <p>
                    Where an organization enables it, DamChat&rsquo;s chat agent is
                    made available through the WhatsApp Business Platform, provided by
                    Meta Platforms, Inc. (&ldquo;Meta&rdquo;). When you message the
                    agent on WhatsApp:
                </p>
                <ul>
                    <li>
                        Your message content, phone number, and associated metadata are
                        transmitted to our servers through Meta&rsquo;s WhatsApp Business
                        API to generate a response.
                    </li>
                    <li>
                        Meta processes this information as well, in its role as the
                        platform provider, in accordance with{" "}
                        <a
                            href="https://www.whatsapp.com/legal/privacy-policy"
                            target="_blank"
                            rel="noreferrer noopener"
                        >
                            WhatsApp&rsquo;s Privacy Policy
                        </a>{" "}
                        and{" "}
                        <a
                            href="https://www.facebook.com/privacy/policy/"
                            target="_blank"
                            rel="noreferrer noopener"
                        >
                            Meta&rsquo;s Privacy Policy
                        </a>
                        .
                    </li>
                    <li>
                        We store the messages and phone number needed to carry on a
                        conversation and provide support, subject to the retention
                        practices described in this policy.
                    </li>
                    <li>
                        Standard message and data rates from your carrier may apply to
                        WhatsApp messages; those charges are outside our control.
                    </li>
                </ul>
                <p>
                    You can stop the conversation with our WhatsApp agent at any time
                    by blocking the business number or asking us to delete your data,
                    as described in <a href="#your-rights">Your Rights and Choices</a>.
                </p>
            </>
        ),
    },
    {
        id: "how-we-share-information",
        title: "How We Share Information",
        body: (
            <>
                <p>We share information only as necessary to run DamChat:</p>
                <ul>
                    <li>
                        <strong>AI model and infrastructure providers.</strong> Your
                        queries and relevant document excerpts are sent to the AI model
                        provider we use to generate answers, and files and data are
                        hosted with our cloud infrastructure provider.
                    </li>
                    <li>
                        <strong>Meta / WhatsApp Business Platform.</strong> As described
                        above, for any conversation conducted over WhatsApp.
                    </li>
                    <li>
                        <strong>Your organization&rsquo;s Admins.</strong> Admins of the
                        organization you belong to can see the questions Users in that
                        organization ask, so they can review and improve the documents
                        DamChat draws on.
                    </li>
                    <li>
                        <strong>Legal and safety.</strong> If required to comply with
                        law, enforce our agreements, or protect the rights, property, or
                        safety of DamChat, our users, or others.
                    </li>
                </ul>
                <p>
                    We do not sell personal information, and we do not share it with
                    third parties for their own independent marketing purposes.
                </p>
            </>
        ),
    },
    {
        id: "storage-security-retention",
        title: "Data Storage, Security & Retention",
        body: (
            <>
                <p>
                    Documents, account records, and conversation history are stored on
                    secured cloud infrastructure with access restricted to authorized
                    personnel and to the organization the data belongs to. We use
                    encryption in transit and access controls to reduce the risk of
                    unauthorized access, though no system can be guaranteed
                    completely secure.
                </p>
                <p>
                    We retain conversation history and uploaded documents for as long
                    as the associated account or organization remains active, or as
                    needed to provide the service, and we delete or anonymize it
                    within a reasonable period after an account is closed or a
                    deletion request is confirmed, unless a longer period is required
                    by law.
                </p>
            </>
        ),
    },
    {
        id: "your-rights",
        title: "Your Rights and Choices",
        body: (
            <>
                <p>Depending on your location, you may have the right to:</p>
                <ul>
                    <li>Request access to the personal information we hold about you.</li>
                    <li>Request correction of inaccurate information.</li>
                    <li>
                        Request deletion of your account, conversation history, or
                        WhatsApp data.
                    </li>
                    <li>Object to or restrict certain processing of your information.</li>
                </ul>
                <p>
                    To exercise any of these rights, contact us using the details in{" "}
                    <a href="/about">About Us</a>. We will respond within a
                    reasonable timeframe and may need to verify your identity before
                    acting on a request.
                </p>
            </>
        ),
    },
    {
        id: "childrens-privacy",
        title: "Children's Privacy",
        body: (
            <p>
                DamChat is intended for use by employees, students, and members of
                organizations that deploy it, and is not directed to children under
                13. We do not knowingly collect personal information from children
                under 13. If you believe a child has provided us with personal
                information, contact us and we will take steps to remove it.
            </p>
        ),
    }
];

export default function PrivacyPolicyPage() {
    return (
        <div className={`${styles.page} ${quicksand.variable} ${inter.variable} ${'wrapper'} ${'container'}`}>
            <main className={styles.card}>
                <h1 className={styles.title}>Privacy Policy</h1>
                <p className={styles.meta}>Last updated: {LAST_UPDATED}</p>
                <p className={styles.intro}>
                    This policy covers DamChat&rsquo;s web application and its chat
                    agent on WhatsApp, and explains what we collect, how we use it,
                    and the choices you have.
                </p>

                <hr className={styles.divider} />

                {sections.map((section, index) => (
                    <section
                        key={section.id}
                        id={section.id}
                        className={styles.section}
                    >
                        <h2 className={styles.sectionTitle}>
                            <span className={styles.sectionNumber}>{index + 1}.</span>
                            {section.title}
                        </h2>
                        {section.body}
                    </section>
                ))}
            </main>
        </div>
    );
}